config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'products/:id/add' => 'products#add', as: 'add_to_cart'

  resources :products
  resources :users do
    member do
      get 'display_cart'
    end
  end

  resources :charges, only: [:new, :create] do

  end

  get 'charges/complete' => 'charges#complete', as: 'complete_charge'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessor :multiplier

  has_many :selecteditems
  has_many :users, through: :selecteditems

  
  # def price_in_dollars
  #   self.price.to_f / 100
  # end

end

app/models/selecteditem.rb
class Selecteditem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product


  # def total_cost
  #   @items = current_user.find
  #
  # end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :selecteditems
  has_many :products, through: :selecteditems


  validates_presence_of :email, :password_digest
  validates_uniqueness_of :email

  has_secure_password

  def cart_total
    cost = self.products.inject(0) do |total, item|
          total + item.price
    end

    return cost
  end

  def build_cart
    cart = self.products.uniq
    cart.each do |item|
        item.multiplier = self.products.where(id: item).length
    end
    return cart
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include SessionHelper

  def new
    @total_cost = current_user.cart_total
    @token = Braintree::ClientToken.generate
    if current_user.customer_id
      render 'repeat'
    else
      render 'new'
    end
  end

  def create
    @total_cost = current_user.cart_total
    nonce = params[:payment_method_nonce]

    # If payment was method was submitted, create a customer
    # Future refactor: add ability to create add. payment methods
    if nonce
      customer_result = Braintree::Customer.create(
        first_name: current_user.first_name,
        last_name: current_user.last_name,
        payment_method_nonce: nonce
      )
      # If customer/method are submitted without error, store customer ID for repeat payments
      if customer_result.success?
        puts customer_result.customer
        current_user.update(customer_id: customer_result.customer.id)
      else
        @errors = customer_result.errors
        render 'new'
      end
    end
    # Either customer ID was just created or it already existed. Now we can process transaction.
    customer_id = current_user.customer_id
    result = Braintree::Transaction.sale(
    customer_id: customer_id,
    amount: "#{@total_cost}",
      options: {
        submit_for_settlement: true
      }
    )
    puts result
    if result.success?
      redirect_to complete_charge_path(result: "Success")
    else
      redirect_to complete_charge_path
    end
  end

  def complete
    result = params[:result]
    if result == "Success"
      current_user.selecteditems.destroy_all
    else
      @error = "Transaction failed :("
    end
  end





end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include SessionHelper
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

  end

  def add
    @product = Product.find(params[:id])
    selection = Selecteditem.new(product: @product, user: current_user)
    if selection.save
      flash[:notice] = selection.product.name + " was added to your cart"
      redirect_to root_url
    else
      # Handle errors(not part of MVP)
    end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in_user(@user)
      redirect_to root_url
    else
      @errors = @user.errors.full_messages
      render "new"
    end
  end

  def destroy
    log_out_user
    redirect_to root_url
  end

  def log_in_user(user)
    session[:user_id] = user.id
  end

  def log_out_user
    session.delete(:user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionHelper

  def display_cart # Should I even include user ID in route?
    @cart = current_user.build_cart
    @total_cost = current_user.cart_total
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user(@user)
      redirect_to root_url
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to @user
    else
      render 'edit'
    end
  end

  #Refactor to destroy individual cart items
  def destroy
    current_user.selecteditems.destroy_all
    redirect_to display_cart_user_path(current_user.id)
  end

  private
      def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password)
      end

      def log_in_user(user)
        session[:user_id] = user.id
      end

end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  def index
    puts "Generate new charge"
    @token = Braintree::ClientToken.generate
  end

  def create
  end

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    if logged_in?
      @current_user = User.find(session[:user_id])
    end
  end

  def logged_in?
    session[:user_id]
  end
end

app/views/charges/complete.html.erb
<% if @error %>
  <p class="text-danger">Transaction Failed. <%= link_to "Try again", display_cart_user_path(current_user) %></li></p>

<% else %>
  <p class="text-success">Transaction Success!</p>
<% end %>

app/views/charges/new.html.erb
<% if @errors %>
  <ul class="text-danger">
  <% @errors.each do |error| %>
    <li><%= error %></li> <!-- Check to see what error outputs -->
  <% end %>
  </ul>
<% end %>
<h3 class="text-center">Click to submit purchase for <%= number_to_currency(@total_cost, precision: 2) %> </h3>

<div class="container">
  <div class="row">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-8">
      <%= form_tag({controller: 'charges', action: 'create'}, method: 'post', id: 'braintree-form', role: 'form') do %>
        <div class="form-group">
          <label for="credit-card-field">Card Number</label>
          <div id="credit-card-field" class="form-control hosted-fields-container"></div>
        </div>

        <div class="form-group">
          <label for="security-code-field">CVV</label>
          <div id="security-code-field"  class="form-control hosted-fields-container"></div>
        </div>

        <div class="form-group">
          <label for="expiration-field">Expiration</label>
           <div id="expiration-field" class="form-control hosted-fields-container"></div>
        </div>

        <div class="form-group">
          <label for="postal-code-field">Postal Code</label>
          <div id="postal-code-field" class="form-control hosted-fields-container"></div>
        </div>
        <input type="submit" class="btn btn-default" value="Submit Transaction">
      </div>
      <div class="col-sm-2">

      </div>
    </div>
  <% end %>
</div>


<script id="braintree-client-token" type="application/json"><%= @token %></script>

<script>
var clientToken = document.getElementById('braintree-client-token').innerHTML;
braintree.setup(clientToken, 'custom', {
  id: 'braintree-form',
  hostedFields: {
    styles: { // hosted fields styles taken from Evan Hahn's solution :D
      'input': {
        'font-family': 'sans-serif',
        'font-size': '16pt',
        'color': 'black'
      },
      'input:focus': {
        'outline': 'none'
      },
      'input.invalid': {
        'color': 'tomato'
      },
      'input.valid': {
        'color': 'limegreen'
      }
    },
    number: {
      selector: '#credit-card-field',
      placeholder: '4111 1111 1111 1111'
    },
    cvv: {
      selector: '#security-code-field',
      placeholder: '123'
    },
    expirationDate: {
      selector: '#expiration-field',
      placeholder: 'MM/YYYY'
    },
    postalCode: {
      selector: '#postal-code-field',
      placeholder: '12345'
    }
  },
});
</script>

app/views/charges/repeat.html.erb
<!-- Refactor to add change payment. Also would want to display current defauly payment credentials -->

<h4>You have a credit card securely stored on file. Click to confirm purchase for <%= number_to_currency(@total_cost, precision: 2) %> </h4>

<%= form_tag({controller: 'charges', action: 'create'}, method: 'post', id: 'braintree-form') do %>
  <input type="submit" class="btn btn-default" value="Submit Transaction">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brain Freeze Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://js.braintreegateway.com/js/braintree-2.24.1.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <header>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%=image_tag("iceCreamLogo.png", class: 'logonav')%>
      <!-- <a class="navbar-brand" href="/">BrainFreeze!  Rare Icecreams</a> -->
    </div>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Brainfreeze Rare Ice Cream!', root_path %></li>
        <% if logged_in? %>
          <li><a href="#">Welcome, <%= current_user.first_name %></a></li>
          <li><%= link_to 'My Cart', display_cart_user_path(current_user) %></li>

        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Login',  login_path %></li>
        <li><%= link_to 'Register', new_user_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>
</header>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<% if flash[:notice] %>
  <p class="text-success"><%= flash[:notice] %><p>
<% end %>

<ul>
  <% @products.each do |item|  %>
    <div class="col-sm-3 product-div">
      <a href="/products/<%= item.id %>">  <%=image_tag("iceCreamLogo.png", class: 'logonav')%></a>
      <p><a href="/products/<%= item.id %>"><%= item.name %></a></p>
    </div>
  <% end %>

</ul>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<ul>

  <li><%= @product.description %></li>
  <li><%= number_to_currency(@product.price, precision: 2) %></li>
  <% if logged_in? %>
    <li><%= link_to "Add to Cart", add_to_cart_path %></li>
  <% end %>

</ul>

app/views/users/display_cart.html.erb
<h2 class="text-center">Welcome to your cart, <%= current_user.first_name %></h2>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
      <ul>
        <% if @cart.length > 0 %>
          <% @cart.each do |item| %>
            <h3><%=link_to "#{item.name}", product_path(item)%></h3>
            <li>Item Price: <%= number_to_currency(item.price, precision: 2) %></li>
            <li>Item Quantity: <%= item.multiplier %></li>
            <li>Total: <%= number_to_currency((item.price * item.multiplier)) %></li>
          <% end %>
            <%= form_tag({controller: 'charges', action: 'new'}, method: 'get') do %>
            <div class="form-group">
              <input type="submit" class="btn btn-default text-center" value="Checkout">
            </div>
            <% end %>
            <%= form_tag({controller: 'users', action: 'destroy'}, method: 'delete') do %>
            <div class="form-group">
              <input type="submit" class="btn btn-default text-center" value="Empty Cart">
            </div>
            <% end %>
        <% else %>
          <h4 class="text-center">Your Cart is empty, go add some brainfreeze!</h4>
        <% end %>
      </ul>


        <h3 class="text-center">Item Total: <%= number_to_currency(@total_cost) %></h4>

    </div>
    <div class="col-sm-2">
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% if @errors %>
<ul>
  <% @errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>


    <h3 class='text-center'>Create a new account!</h3>


<div class="container">
  <div class="row">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-8">
      <%= form_for :user, url: {action: 'create'}, method: :post, html: {role: 'form'} do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <%= f.submit "Create User", class: 'btn btn-default' %>
      <% end %>
    </div>
    <div class="col-sm-2">

    </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<p>Hello! Would you like to make a payment?</p>
<button style="width:100px;height:50px" href="/client_token/<%= @token %>"></button>